// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"
import oauth2 "github.com/mbict/go-oauth2"
import time "time"
import url "net/url"

// AccessTokenRequest is an autogenerated mock type for the AccessTokenRequest type
type AccessTokenRequest struct {
	mock.Mock
}

// Client provides a mock function with given fields:
func (_m *AccessTokenRequest) Client() oauth2.Client {
	ret := _m.Called()

	var r0 oauth2.Client
	if rf, ok := ret.Get(0).(func() oauth2.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(oauth2.Client)
		}
	}

	return r0
}

// Code provides a mock function with given fields:
func (_m *AccessTokenRequest) Code() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GrantScope provides a mock function with given fields: scope
func (_m *AccessTokenRequest) GrantScope(scope ...string) {
	_va := make([]interface{}, len(scope))
	for _i := range scope {
		_va[_i] = scope[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// GrantedScopes provides a mock function with given fields:
func (_m *AccessTokenRequest) GrantedScopes() oauth2.Scope {
	ret := _m.Called()

	var r0 oauth2.Scope
	if rf, ok := ret.Get(0).(func() oauth2.Scope); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(oauth2.Scope)
		}
	}

	return r0
}

// RedirectUri provides a mock function with given fields:
func (_m *AccessTokenRequest) RedirectUri() *url.URL {
	ret := _m.Called()

	var r0 *url.URL
	if rf, ok := ret.Get(0).(func() *url.URL); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*url.URL)
		}
	}

	return r0
}

// RequestValues provides a mock function with given fields:
func (_m *AccessTokenRequest) RequestValues() url.Values {
	ret := _m.Called()

	var r0 url.Values
	if rf, ok := ret.Get(0).(func() url.Values); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(url.Values)
		}
	}

	return r0
}

// RequestedAt provides a mock function with given fields:
func (_m *AccessTokenRequest) RequestedAt() time.Time {
	ret := _m.Called()

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// RequestedScopes provides a mock function with given fields:
func (_m *AccessTokenRequest) RequestedScopes() oauth2.Scope {
	ret := _m.Called()

	var r0 oauth2.Scope
	if rf, ok := ret.Get(0).(func() oauth2.Scope); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(oauth2.Scope)
		}
	}

	return r0
}

// Session provides a mock function with given fields:
func (_m *AccessTokenRequest) Session() oauth2.Session {
	ret := _m.Called()

	var r0 oauth2.Session
	if rf, ok := ret.Get(0).(func() oauth2.Session); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(oauth2.Session)
		}
	}

	return r0
}
