// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"
import oauth2 "github.com/mbict/go-oauth2"
import time "time"

// Session is an autogenerated mock type for the Session type
type Session struct {
	mock.Mock
}

// ExpiresAt provides a mock function with given fields:
func (_m *Session) ExpiresAt() time.Time {
	ret := _m.Called()

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// Id provides a mock function with given fields:
func (_m *Session) Id() oauth2.SessionId {
	ret := _m.Called()

	var r0 oauth2.SessionId
	if rf, ok := ret.Get(0).(func() oauth2.SessionId); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(oauth2.SessionId)
	}

	return r0
}

// UserId provides a mock function with given fields:
func (_m *Session) UserId() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
